2022-l3l1/trunk/siteWeb/src/ProduitApp/urls.py
"""
all the urls used by  ProduitApp

"""

from django.urls import path
from . import views
from .views import modifier_produit, produit_detail,supprimer_produit_brut,supprimer_autre_produit, autre_produit_detail,modifier_autre_produit,modifier_categorie,supprimer_categorie
from django.conf import settings
from django.conf.urls.static import static

app_name = 'ProduitApp'

urlpatterns = [
    path('produit_brut/',views.produit_brut,name='produit_brut'),
   # path('produit_brut/add/', views.add_produit_brut, name='add_produit_brut'),
    path('produit_brut/modifier/<int:pk>/', modifier_produit.as_view(), name='modifier_produit'),
    path('produit_brut/detail/<int:pk>/', produit_detail.as_view(), name='produit_detail'),
    path('produit_brut/supprimer/<int:pk>/', supprimer_produit_brut.as_view(), name='supprimer_produit_brut'),
    path('historique_prix_achat_quintal/<int:pk>/', views.historique_prix_achat_quintal, name='historique_prix_achat_quintal'),


    path('autre_produit/',views.autre_produit,name='autre_produit'),
    path('autre_produit/modifier/<int:pk>/', modifier_autre_produit.as_view(), name='modifier_autre_produit'),
    path('autre_produit/add/', views.add_autre_produit, name='add_autre_produit'),
    path('autre_produit/detail/<int:pk>/', autre_produit_detail.as_view(), name='autre_produit_detail'),
    path('autre_produit/supprimer/<int:pk>/', supprimer_autre_produit.as_view(), name='supprimer_autre_produit'),




    path('cadre/',views.cadre ,name='cadre'),
    path('cadre/create_cadre', views.createCadre, name='create_cadre'),
    path('cadre/supprimer/<int:id>/', views.supprimer_cadre, name='supprimer_cadre'),
    path('cadre/modifier/<int:pk>/', views.modifier_cadre.as_view(), name='modifier_cadre'),
    path('tri_cadre/<str:tri>/', views.tri_cadre, name='tri_cadre'),


    path('produitApp/', views.index, name='produitApp'),


    path('categorie/', views.categorie, name='categorie'),
    path('create_categorie/', views.create_category, name='create_categorie'),
    path('categorie/modifier/<int:pk>/', modifier_categorie.as_view(), name='modifier_categorie'),
    path('categorie/supprimer/<int:pk>/',supprimer_categorie.as_view(),name='supprimer_categorie'),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2022-l3l1/trunk/siteWeb/src/StatApp/urls.py
"""
all the urls used by  StatApp

"""

from django.urls import path
from . import views


app_name = 'StatApp'

urlpatterns = [
    path('statistique/', views.all_stat, name="statistique"),

]

2022-l3l1/trunk/siteWeb/src/siteWeb/urls.py
from django.contrib import admin
from django.urls import path, include

import VenteApp
import ProduitApp
import ClientApp
import AchatApp
import FournisseursApp




from ClientApp import views
from VenteApp import views
from ProduitApp import views
from AchatApp import views
from .views import index, venue_pdf, loginPage, registerPage, logOutUser, achat, alertesStock, client, fournisseur
from .views import vente
from FournisseursApp import views


urlpatterns = [
    path('login/', loginPage, name="login"),
    path('logout/', logOutUser, name="logout"),
    
    path('alertes/', alertesStock, name="alertes"),
    path('client/', client, name="client"),
    path('compte/', registerPage, name="compte"),
    path('fournisseur/', fournisseur, name="fournisseur"),
    path('vente/', vente, name="vente"),

    path("", index, name="index"),

    path('venue_pdf/', venue_pdf, name="venue_pdf"),
    path('compteApp/', ClientApp.views.index, name='compteApp'),

    #VENTE URL
    path('venteApp/', include('VenteApp.urls',namespace='venteApp')),
    path('proformat/', VenteApp.views.proformat, name="proformat"),
    path('create_order/', VenteApp.views.createOrder, name="create_order"),
    path('update_order/<str:pk>/', VenteApp.views.updateOrder, name="update_order"),
    path('delete_order/<str:pk>/', VenteApp.views.deleteOrder, name="delete_order"),
    path('recherche/', VenteApp.views.searchBar, name="search"),

    #PRODUIT URL
    path('', include('ProduitApp.urls')),

    path('', include('StatApp.urls')),

    path('admin/', admin.site.urls),
    #FournisseurApp
    
    path('',include(('FournisseursApp.urls','FournisseursApp'),namespace='FournisseursApp')),

    path('fournisseurs/',FournisseursApp.views.index,name='FournisseursApp'),
    path('ajout_fournisseurs/',FournisseursApp.views.ajout_fournisseurs,name='ajout_fournisseurs'),
    path('fournisseurs/supprimer/<int:pk>/', FournisseursApp.views.FournisseurDeleteView.as_view(), name='supprimer_fournisseur'),
    #AchatApp
    path('achat/',AchatApp.views.index,name='achat'),
    path('',include(('AchatApp.urls','AchatApp'),namespace='AchatApp')),
     path('ajouter_facture/fournisseur/<int:fournisseur_id>/achat/<int:achat_id>/', AchatApp.views.ajouter_facture, name='ajouter_facture'),
]

2022-l3l1/trunk/siteWeb/src/ProduitApp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView
from django.template import loader

from .forms import ProduitBrutForm, CadreForms, AutreProduitForm


# Create your views here.

from django.contrib import messages
from django.shortcuts import render, redirect,get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse
from .models import ProduitBrut, Produit, Categorie, Cadre, AutreProduit, CategorieFer,HistoriquePrixAchatQuintal
from .forms import CategorieForm, CadreForms

def index(request):
    """
    Vue qui retourne la page d'accueil du site.

    Arguments:
    - request: l'objet HttpRequest envoyé par le navigateur

    Returns:
    - HttpResponse : la réponse HTTP avec la page HTML demandée (produit_base.html)
    """
    return render(request, 'ProduitApp/produit_base.html')


"""
view pour afficher les autres produits 
"""
def autre_produit(request):
    """
    Vue pour afficher tous les autres produits dans le modèle AutreProduit
    et les afficher dans un template HTML approprié.

    Arguments:
    - request: objet HttpRequest contenant les détails de la requête HTTP entrante.

    Renvoie:
    - HttpResponse: réponse HTTP renvoyée à l'utilisateur, contenant le contenu HTML
                    généré dynamiquement pour afficher tous les autres produits dans le modèle AutreProduit.
"""
    autre_produit = AutreProduit.objects.all()
    return render(request, 'ProduitApp/autre_produit.html',
                            {'autres_produits': autre_produit})




"""
view pour afficher les produits brut (barre de fer)
"""
def produit_brut(request):
    """
    Renvoie la page de liste des produits bruts.

    Args:
        request: La requête HTTP envoyée par le client.

    Returns:
        La réponse HTTP avec la page de liste des produits bruts rendue à l'aide d'un template.
        Le contexte contient la liste de tous les produits bruts stockés dans la base de données.
    """
    produits_bruts = ProduitBrut.objects.all()
    return render(request, 'ProduitApp/produits_bruts.html',
                            {'produits_bruts': produits_bruts})

"""
view pour afficher les cadres 
"""
def cadre(request):
    """
    Vue qui affiche la liste des cadres.

    Args:
        request: la requête HTTP reçue.

    Returns:
        Un objet HttpResponse contenant le rendu HTML de la page d'affichage des cadres.

    """
    cadres = Cadre.objects.all()

    return render(request, 'ProduitApp/cadres.html', {'cadres': cadres})




def categories(request):
    """
    Cette fonction prend une requête HTTP en entrée et récupère toutes les catégories depuis la base de données.
    Elle retourne ensuite une réponse HTTP qui affiche toutes les catégories dans un template appelé 'ProduitApp/categorie.html'.

    Arguments:
    - request: requête HTTP

    Retour:
    - HTTP response : réponse HTTP qui affiche toutes les catégories

    """
    categories= Categorie.objects.all()
    return render(request, 'ProduitApp/categorie.html', 
                  {'categories': categories})


def createCadre(request):
    """
    Cette fonction permet de créer un nouveau cadre en utilisant un formulaire.

    Args:
    - request: une requête HTTP.

    Returns:
    - Une page HTML affichant un formulaire pour la création d'un nouveau cadre.
    - Si les données soumises dans le formulaire sont valides, la fonction crée un nouveau cadre et redirige l'utilisateur vers la page d'accueil des cadres.
    """
    form = CadreForms()
    if request.method == 'POST':
        form= CadreForms(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/cadre/')
    return render(request, 'ProduitApp/create_cadre.html', {'form': form})




def supprimer_cadre(request, id):
    """
    Supprime un objet Cadre spécifié par son ID de la base de données.

    :param request: Objet HttpRequest contenant les données de la requête.
    :type request: django.http.HttpRequest
    :param id: ID de l'objet Cadre à supprimer.
    :type id: int
    :return: Redirige l'utilisateur vers la page '/cadre/'.
    :rtype: django.http.HttpResponseRedirect
    """
    cadre = Cadre.objects.get(id=id)
    cadre.delete()
    return redirect('/cadre/')



class modifier_cadre(UpdateView):
    """
    Classe basée sur UpdateView qui permet la modification d'un objet Cadre existant.

    :ivar model: Classe du modèle à utiliser pour la vue (obligatoire).
    :vartype model: django.db.models.Model
    :ivar form_class: Classe du formulaire à utiliser pour la vue (obligatoire).
    :vartype form_class: django.forms.ModelForm
    :ivar template_name: Nom du modèle à utiliser pour le rendu de la vue.
    :vartype template_name: str
    """
    model = Cadre
    form_class = CadreForms
    template_name = 'ProduitApp/modifier_cadre.html'
    def form_valid(self, form):
        """
        Méthode appelée lorsque le formulaire de modification d'un objet Cadre est valide.

        :param form: Formulaire validé avec les données de la requête.
        :type form: django.forms.ModelForm
        :return: Redirige l'utilisateur vers la page '/cadre/'.
        :rtype: django.http.HttpResponseRedirect
        """
        form.save()
        return redirect('/cadre/')



def tri_cadre(request, tri):
    if tri == 'Cadre_choix':
        # Si le paramètre 'tri' est égal à 'Cadre_choix'
        # Alors, trier les objets 'Cadre' par l'attribut 'cadre_choix'
        cadre = Cadre.objects.order_by('cadre_choix')

    elif tri == 'Article_choix':
        # Sinon, si le paramètre 'tri' est égal à 'Article_choix'
        # Alors, trier les objets 'Cadre' par l'attribut 'article_choix'
        cadre = Cadre.objects.order_by('article_choix')

    elif tri == 'prix_metre':
        # Sinon, si le paramètre 'tri' est égal à 'prix_metre'
        # Alors, trier les objets 'Cadre' par l'attribut 'prix_metre'
        cadre = Cadre.objects.order_by('prix_metre')

    elif tri == 'longueur':
        # Sinon, si le paramètre 'tri' est égal à 'longueur'
        # Alors, trier les objets 'Cadre' par l'attribut 'longueur'
        cadre = Cadre.objects.order_by('longueur')

    elif tri == 'largeur':
        # Sinon, si le paramètre 'tri' est égal à 'largeur'
        # Alors, trier les objets 'Cadre' par l'attribut 'largeur'
        cadre = Cadre.objects.order_by('largeur')

    elif tri == 'crochet':
        # Sinon, si le paramètre 'tri' est égal à 'crochet'
        # Alors, trier les objets 'Cadre' par l'attribut 'crochet'
        cadre = Cadre.objects.order_by('crochet')

    elif tri == 'prix_service':
        # Sinon, si le paramètre 'tri' est égal à 'prix_service'
        # Alors, trier les objets 'Cadre' par l'attribut 'prix_service'
        cadre = Cadre.objects.order_by('prix_service')

    elif tri == 'chute':
        # Sinon, si le paramètre 'tri' est égal à 'chute'
        # Alors, trier les objets 'Cadre' par l'attribut 'chute'
        cadre = Cadre.objects.order_by('chute')

    elif tri == 'consommation_sans_chute':
        # Sinon, si le paramètre 'tri' est égal à 'consommation_sans_chute'
        # Alors, trier les objets 'Cadre' par l'attribut 'consommation_sans_chute'
        cadre = Cadre.objects.order_by('consommation_sans_chute')

    elif tri == 'consommation':
        # Sinon, si le paramètre 'tri' est égal à 'consommation'
        # Alors, trier les objets 'Cadre' par l'attribut 'consommation'
        cadre = Cadre.objects.order_by('consommation')

    elif tri == 'crochet_opti':
        # Sinon, si le paramètre 'tri' est égal à 'crochet_opti'
        # Alors, trier les objets 'Cadre' par l'attribut 'crochet_opti'
        cadre = Cadre.objects.order_by('crochet_opti')

    elif tri == 'chute_valeur':
        # Sinon, si le paramètre 'tri' est égal à 'chute_valeur'
        # Alors, trier les objets 'Cadre' par l'attribut 'chute_valeur'
        cadre = Cadre.objects.order_by('chute_valeur')

    elif tri == 'max':
        # Sinon, si le paramètre 'tri' est égal à 'max'
        # Alors, trier les objets 'Cadre' par l'attribut 'max'
        cadre = Cadre.objects.order_by('max')

    elif tri == 'prix':
        # Sinon, si le paramètre 'tri' est égal à 'prix'
        # Alors, trier les objets 'Cadre' par l'attribut 'prix'
        cadre = Cadre.objects.order_by('prix')

    else:
        # Sinon, si le paramètre 'tri' n'est pas égal à un des choix ci-dessus
        # Alors, renvoyer tous les objets 'Cadre' non triés
        cadre = Cadre.objects.all()
    return render(request, 'ProduitApp/cadres.html', {'cadres': cadre})


def categorie(request):
    """
    Affiche une liste de toutes les catégories d'objets de produit à l'exception de 'produit brut' et 'cadre'.

    :param request: Objet HttpRequest contenant les données de la requête.
    :type request: django.http.HttpRequest
    :return: HttpResponse contenant la page de liste des catégories d'objets de produit.
    :rtype: django.http.HttpResponse
    """
    categories = Categorie.objects.exclude(name__in=['produit brut', 'cadre'])
    context = {
        'categories': categories,
    }
    return render(request, 'ProduitApp/categorie.html', context)


def create_category(request):
    """
    Affiche un formulaire de création de catégorie pour les objets de produit et crée une nouvelle catégorie lorsqu'il est soumis.

    :param request: Objet HttpRequest contenant les données de la requête.
    :type request: django.http.HttpRequest
    :return: Redirige l'utilisateur vers la page '/categorie/' après la création d'une nouvelle catégorie, ou affiche un formulaire de création de catégorie.
    :rtype: django.http.HttpResponseRedirect ou django.http.HttpResponse
    """
    form = CategorieForm
    categories=Categorie.objects.all()

    if request.method == 'POST':

2022-l3l1/trunk/siteWeb/src/ProduitApp/templates/ProduitApp/autre_produit_detail.html
{% extends 'ProduitApp/produit_base.html' %}

{% block content %}
    <h1>Détails du produit : {{ object.designation }}</h1>
    <p>catégorie : {{ object.categorie}} </p>
    <p>prix d'achat {{ object.prix_achat}}</p>
    <p>prix de vente:  {{ object.prix_vente}}</p>
    <p>stock :  {{ object.quantite}}</p>
    <p>quantite alerte: {{ object.stock_alerte}}</p>

    <!-- Lien vers la page de modification du produit -->
    <a href="{% url 'ProduitApp:modifier_autre_produit' object.pk %}">Modifier</a>

    <!-- Lien pour supprimer le produit -->
    <a href="{% url 'ProduitApp:supprimer_autre_produit' object.pk %}">supprimer</a>

    <!-- Bouton pour annuler et retourner à la liste des produits -->
    <button><a href="{% url 'ProduitApp:autre_produit' %}"> Annuler</a></button>

{% endblock %}

2022-l3l1/trunk/siteWeb/src/ProduitApp/templates/ProduitApp/cadres.html

{% block content %}
    <!-- Le bloc content représente le contenu de la page -->
    <h1>Liste des cadres</h1>
    <br>
    <table border="1" style="border-collapse:collapse;">
        <!-- On crée un tableau HTML pour afficher les cadres -->
        <thead>
        <tr>
            <!-- Les colonnes du tableau sont cliquables pour trier les cadres en fonction de l'attribut correspondant -->
            <th><a href="{% url 'ProduitApp:tri_cadre' 'cadre_choix' %}">Cadre</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'article_choix' %}">Type article</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'prix_metre' %}">Prix mètre</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'longueur' %}">Longueur</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'largeur' %}">Largeur</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'crochet' %}">Crochet</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'prix_service' %}">Prix service</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'chute' %}">Chute</a></th>

            <th><a href="{% url 'ProduitApp:tri_cadre' 'consommation_sans_chute' %}">Consommation sans chute</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'consommation' %}">Consommation</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'crochet_opti' %}">Crochet optimisé</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'chute_valeur' %}">Taille chute</a></th>
            <th><a href="{% url 'ProduitApp:tri_cadre' 'max' %}">Max</a></th>

            <th><a href="{% url 'ProduitApp:tri_cadre' 'prix' %}">Prix total</a></th>
        <tr>
        </thead>
        <tbody>
        <!-- On boucle sur les cadres passés en paramètre pour les afficher dans le tableau -->
        {% for cadre in cadres %}
            <tr>
                <!-- On affiche les attributs de chaque cadre dans les colonnes correspondantes -->
                <td>{{ cadre.cadre_choix }}</td>
                <td>{% for produit in cadre.article_choix.all %}{{ produit }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
                <td>{{ cadre.prix_metre }}</td>
                <td>{{ cadre.longueur }}</td>
                <td>{{ cadre.largeur }}</td>
                <td>{{ cadre.crochet_opti }}</td>
                <td>{{ cadre.prix_service }}</td>
                <td>{{ cadre.chute }}</td>
                <td>{{ cadre.consommation_sans_chute }}</td>
                <td>{{ cadre.consommation }}</td>
                <td>{{ cadre.crochet }}</td>
                <td>{{ cadre.chute_valeur }}</td>
                <td>{{ cadre.max }}</td>
                <td>{{ cadre.prix }}</td>

                <td><a href="{% url 'ProduitApp:modifier_cadre' cadre.id %}">Modifier</a></td>
                <td><a href="{% url 'ProduitApp:supprimer_cadre' cadre.id %}">Supprimer</a></td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <button>
        <a href="{% url 'ProduitApp:create_cadre' %}">Créer un cadre</a>
    </button>
{% endblock %}



2022-l3l1/trunk/siteWeb/src/ProduitApp/templates/ProduitApp/categorie.html
{% extends 'ProduitApp/produit_base.html' %}

{% block content %}
    <!-- Bloc qui affiche un tableau contenant la liste des catégories -->
    <table border="2" style="border-collapse:collapse;">
        <thead>
        <tr>
            <th>Libellé</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <!-- Boucle qui parcourt la liste des catégories et affiche leur nom -->
        {% for categorie in categories %}
            <tr>
                <td>{{ categorie.name }}</td>
                <td>
                    <!-- Liens pour modifier ou supprimer la catégorie en question -->
                    <a href="{% url 'ProduitApp:modifier_categorie' categorie.pk %}">Modifier</a>
                    <a href="{% url 'ProduitApp:supprimer_categorie' categorie.pk %}">supprimer</a>
                </td>
            </tr>
            {% empty %}
            <!-- Cas où il n'y a pas de catégorie -->
            <tr>
                <td colspan="2">Aucune catégorie trouvée.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <br>
    <!-- Bouton pour ajouter une nouvelle catégorie -->
    <button><a href="{%url 'ProduitApp:create_categorie'%}" style="text-decoration:none;">Ajouter une catégorie </a></button>

{% endblock %}

2022-l3l1/trunk/siteWeb/src/ProduitApp/templates/ProduitApp/modifier_categorie.html
{% extends 'ProduitApp/produit_base.html' %}

{% block content %}
    <!-- Le bloc content contient le formulaire de modification de la catégorie -->
    <h1>Modifier la catégorie</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }} <!-- Affiche le formulaire généré automatiquement -->
        <input type="submit" value="Modifier">
    </form>
{% endblock %}

2022-l3l1/trunk/siteWeb/src/ProduitApp/templates/ProduitApp/modifier_produit.html
{% extends 'ProduitApp/produit_base.html' %} <!-- On étend la base de la page produit_base.html -->

{%load static %} <!-- On charge les fichiers statiques tels que les fichiers CSS, les images, etc. -->

{% block content %} <!-- On crée un bloc de contenu -->
    <h1>Modifier produit brut</h1> <!-- On affiche le titre de la page -->

    <form method="post"> <!-- On crée un formulaire pour soumettre les données -->
        {% csrf_token %} <!-- On inclut un token CSRF pour sécuriser le formulaire -->
        {{ form.as_p }} <!-- On affiche le formulaire de modification du produit brut -->
        <input type="submit" value="Modifier"> <!-- On crée un bouton pour soumettre les données -->
    </form>

    <button><a href="{% url 'ProduitApp:historique_prix_achat_quintal' pk=object.pk %}">Historique</a></button> <!-- On crée un bouton pour afficher l'historique des prix d'achat en quintal -->


    {% block js_block %} <!-- On crée un bloc pour insérer du code JavaScript -->
        <script type="text/javascript" src="{% static 'js/calculs_produit_brut.js' %}"></script> <!-- On inclut le fichier JavaScript pour réaliser des calculs -->
    {% endblock %} <!-- On termine le bloc pour insérer du code JavaScript -->

{% endblock %} <!-- On termine le bloc de contenu -->

2022-l3l1/trunk/siteWeb/src/ProduitApp/templates/ProduitApp/produit_base.html
<!-- Début du document HTML -->
<html lang="fr">
<head>
    <!-- Les métadonnées -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Le titre de la page -->
    <title>Interface produit</title>
</head>
<body>
<!-- La barre de navigation -->
<nav>
    <ul>
        <li><a href="{% url 'ProduitApp:produit_brut' %}">Produits bruts</a></li>
        <li><a href="{% url 'ProduitApp:cadre' %}">Cadres</a></li>
        <li><a href="{% url 'ProduitApp:autre_produit' %}">Autres produits</a></li>
    </ul>
    <!-- Bouton pour accéder à la page des catégories -->
    <button><a href="{% url 'ProduitApp:categorie' %}" > catégories </a></button>
</nav>
<!-- Contenu spécifique à chaque page -->
{% block content %}{% endblock %}
</body>
</html>

2022-l3l1/trunk/siteWeb/src/ProduitApp/templates/ProduitApp/produit_detail.html
{% extends 'ProduitApp/produit_base.html' %}

{% block content %}
    <h1>Détails du produit : {{ object.designation }}</h1>

    <!-- Affichage des détails du produit -->
    <p>catégorie :  {{ object.categorie }} </p>
    <p>prix d'achat en quintal : {{ object.prix_achat_quintal}} </p>
    <p>prix d'achat en metre : {{ object.prix_achat_metre}} </p>
    <p>prix d'achat en barre : {{ object.prix_achat_barre}} </p>
    <br>
    <br>
    <p>prix de vente en quintal :{{ object.prix_quintal}}</p>
    <p>prix de vente en mètre {{ object.prix_metre}}</p>
    <p>prix de vente en barre: {{ object.prix_barre}}</p>
    <br><br>
    <p>stock en quintal :  {{ object.stock_quintal}}</p>
    <p>stock en metre :  {{ object.stock_metre}}</p>
    <p>stock en barre :  {{ object.stock_barre}}</p>
    <br><br>
    <p>TVA : {{ object.TVA }}</p>

    <!-- Liens pour modifier ou supprimer le produit -->
    <a href="{% url 'ProduitApp:modifier_produit' object.pk %}">Modifier</a>
    <a href="{% url 'ProduitApp:supprimer_produit_brut' object.pk %}">supprimer</a>

    <button><a href="{% url 'ProduitApp:produit_brut' %}"> Annuler</a></button>
{% endblock %}

2022-l3l1/trunk/siteWeb/src/ProduitApp/templates/ProduitApp/produits_bruts.html
{% extends 'ProduitApp/produit_base.html' %}

{% block content %}
    <!-- Ce bloc "content" sera rempli avec le contenu spécifique à cette template. -->
    <h1>Liste des produits brut</h1>
    <table border="2" style="border-collapse:collapse;">
        <thead>
        <tr>
            <!-- Les en-têtes de colonnes -->
            <th>Désignation</th>
            <th>TVA</th>
            <th>diametre</th>
            <th>Prix d'achat par mètre</th>
            <th>prix de vente par mètre</th>
            <th>quantite en stock (m)</th>
            <th>Prix d'achat en barre(à l'unité) </th>
            <th>prix de vente par barre</th>
            <th>quantite en stock en barre</th>
            <th>Prix d'achat par quintal</th>
            <th>prix de vente par quintal</th>
            <th>quantite en stock (quintal)</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <!-- Boucle for pour parcourir chaque produit brut et afficher ses informations dans une ligne du tableau -->
        {% for produit in produits_bruts %}
            <tr>
                <td>{{ produit.designation }}</td>
                <td>{{produit.TVA}}</td>
                <td>{{produit.type_fer}}</td>
                <td>{{ produit.prix_achat_metre}}</td>
                <td>{{ produit.prix_metre}}</td>
                <td>{{ produit.stock_metre }}</td>
                <td>{{ produit.prix_achat_barre }}</td>
                <td>{{produit.prix_barre}}</td>
                <td>{{produit.stock_barre}}</td>
                <td>{{produit.prix_achat_quintal}}</td>
                <td>{{produit.prix_quintal}}</td>
                <td>{{produit.stock_quintal}}</td>

                <!--
                    Les liens pour modifier ou afficher les détails d'un produit sont commentés.

                    <a href="{% url 'ProduitApp:modifier_produit' produit.id %}">Modifier</a>
                    <td><a href="{% url 'ProduitApp:produit_detail' produit.id %}">Détails</a></td>

                    -->

                <!-- Lien pour afficher les détails d'un produit -->
                <td><a href="{{ produit.get_absolute_url }}">Détails</a></td>


            </tr>

        {% endfor %}
        </tbody>
    </table>
    <br><br>
{% endblock %}