2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/urls.py
from django.contrib import admin
from django.urls import path, include
from FournisseursApp import views
from .views import FournisseurUpdateView

from FournisseursApp.views import FournisseurDeleteView
urlpatterns=[
    path('fournisseurs/',views.index,name='fournisseurs'),
    path('ajout_fournisseurs/', views.ajout_fournisseurs, name='ajout_fournisseurs'),
   path('fournisseurs/supprimer/<int:pk>/', FournisseurDeleteView.as_view(), name='supprimer_fournisseur'),
   path('<int:pk>/modifier/', FournisseurUpdateView.as_view(), name='modifier_fournisseur'),
   path('fournisseurs/search/', views.search_fournisseurs, name='search_fournisseurs'),
path('tri_fournisseurs/<str:tri>/', views.tri_fournisseurs, name='tri_fournisseurs'),
path('fournisseurs/factures_detail/<int:pk>/', views.factures_detail, name='factures_detail'),

]
"""path('fournisseurs/facture_ajout/<int:pk>/', views.facture_ajout, name='facture_ajout'),
path('fournisseurs/factures_detail/<int:pk>/', views.factures_detail, name='factures_detail'),"""




2022-l3l1/tags/siteWeb.2/siteWeb/src/StatApp/urls.py
"""
all the urls used by  StatApp

"""

from django.urls import path
from . import views


app_name = 'StatApp'

urlpatterns = [
    path('statistique/', views.all_stat, name="statistique"),

]

2022-l3l1/tags/siteWeb.2/siteWeb/src/siteWeb/urls.py
from django.contrib import admin
from django.urls import path, include

import VenteApp
import ProduitApp
import ClientApp
import AchatApp
import FournisseursApp




from ClientApp import views
from VenteApp import views
from ProduitApp import views
from AchatApp import views
from .views import index, venue_pdf, loginPage, registerPage, logOutUser, achat, alertesStock, client, fournisseur
from .views import vente
from FournisseursApp import views


urlpatterns = [
    path('login/', loginPage, name="login"),
    path('logout/', logOutUser, name="logout"),
    
    path('alertes/', alertesStock, name="alertes"),
    path('client/', client, name="client"),
    path('compte/', registerPage, name="compte"),
    path('fournisseur/', fournisseur, name="fournisseur"),
    path('vente/', vente, name="vente"),

    path("", index, name="index"),

    path('venue_pdf/', venue_pdf, name="venue_pdf"),
    path('compteApp/', ClientApp.views.index, name='compteApp'),

    #VENTE URL
    path('venteApp/', include('VenteApp.urls',namespace='venteApp')),
    path('proformat/', VenteApp.views.proformat, name="proformat"),
    path('create_order/', VenteApp.views.createOrder, name="create_order"),
    path('update_order/<str:pk>/', VenteApp.views.updateOrder, name="update_order"),
    path('delete_order/<str:pk>/', VenteApp.views.deleteOrder, name="delete_order"),
    path('recherche/', VenteApp.views.searchBar, name="search"),

    #PRODUIT URL
    path('', include('ProduitApp.urls')),

    path('', include('StatApp.urls')),

    path('admin/', admin.site.urls),
    #FournisseurApp
    
    path('',include(('FournisseursApp.urls','FournisseursApp'),namespace='FournisseursApp')),

    path('fournisseurs/',FournisseursApp.views.index,name='FournisseursApp'),
    path('ajout_fournisseurs/',FournisseursApp.views.ajout_fournisseurs,name='ajout_fournisseurs'),
    path('fournisseurs/supprimer/<int:pk>/', FournisseursApp.views.FournisseurDeleteView.as_view(), name='supprimer_fournisseur'),
    #AchatApp
    path('achat/',AchatApp.views.index,name='achat'),
    path('',include(('AchatApp.urls','AchatApp'),namespace='AchatApp')),
     path('ajouter_facture/fournisseur/<int:fournisseur_id>/achat/<int:achat_id>/', AchatApp.views.ajouter_facture, name='ajouter_facture'),
]

2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/models.py
from django.db import models  #Importe les modèles nécessaires à l'utilisation de la base de données.
from django.core.validators import RegexValidator  #Un module Django qui permet de valider une expression régulière
from django.urls import reverse  #Permet d'avoir accès au bon URL 

class Fournisseurs(models.Model):
    Raison_social = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    phoneNumberRegex = RegexValidator(regex = r"^\+?1?\d{8,15}$")
    Numero_Telephone = models.CharField(validators=[phoneNumberRegex], max_length=16, unique=True)
    Fax = models.CharField(validators=[phoneNumberRegex], max_length=100, null=True, blank=True)
    Versement = models.FloatField(default=0)
    Dette = models.FloatField(default=0)
    def __str__(self):  
        return self.Raison_social 

2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/forms.py
from django import forms
from .models import Fournisseurs
class FournisseurForm(forms.ModelForm):
    class Meta:
        model = Fournisseurs
        fields = ['Raison_social','email','Numero_Telephone','Fax']

2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/views.py
from django.shortcuts import render
from django.shortcuts import render
from .models import Fournisseurs
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from .models import Fournisseurs
from .forms import FournisseurForm
# Create your views here.



def index(request):
    return render(request,"fournisseurs.html",{'fournisseurs':Fournisseurs.objects.all()})# Create your views here.

from django.shortcuts import render, redirect


from django.shortcuts import render, redirect
from .forms import FournisseurForm

def ajout_fournisseurs(request):
    if request.method == 'POST':
        fournisseur_form = FournisseurForm(request.POST,request.FILES)
        if fournisseur_form.is_valid():
            fournisseur_form.save()
            fournisseur_form.clean()
            fournisseur_form = FournisseurForm()
    else:
        fournisseur_form = FournisseurForm()
    return render(request, 'ajout_fournisseurs.html', {'fournisseur_form': fournisseur_form})





from django.views.generic import DeleteView
from django.urls import reverse_lazy


class FournisseurDeleteView(DeleteView):
    model = Fournisseurs
    template_name = 'supprimer_fournisseurs.html'
    success_url = reverse_lazy('FournisseursApp:fournisseurs')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Fournisseur'] = self.object
        return context
from django.views.generic.edit import UpdateView


class FournisseurUpdateView(UpdateView):
    model = Fournisseurs
    form_class = FournisseurForm
    template_name = 'modifier_fournisseur.html'
    
    def get_success_url(self):
        return reverse_lazy('FournisseursApp:fournisseurs')


from django.shortcuts import render
from django.db.models import Q
from .models import Fournisseurs

def search_fournisseurs(request):
    query = request.GET.get('search_query')
    fournisseurs = Fournisseurs.objects.filter(Q(id__icontains=query) | Q(Raison_social__icontains=query))
    context = {'fournisseurs': fournisseurs}
    return render(request, 'fournisseurs.html', context)

def tri_fournisseurs(request, tri):
    if tri == 'id':
        fournisseurs = Fournisseurs.objects.order_by('id')
    elif tri == 'Raison_social':
        fournisseurs = Fournisseurs.objects.order_by('Raison_social')
    elif tri == 'email':
        fournisseurs = Fournisseurs.objects.order_by('email')
    elif tri == 'Numero_Telephone':
        fournisseurs = Fournisseurs.objects.order_by('Numero_Telephone')
    elif tri == 'Fax':
        fournisseurs = Fournisseurs.objects.order_by('Fax')
    elif tri == 'Versement':
        fournisseurs = Fournisseurs.objects.order_by('Versement')
    elif tri == 'Dette':
        fournisseurs = Fournisseurs.objects.order_by('Dette')
    elif tri == 'Facture':
        fournisseurs = Fournisseurs.objects.order_by('Facture')
    else:
        fournisseurs = Fournisseurs.objects.all()
    return render(request, 'fournisseurs.html', {'fournisseurs': fournisseurs})



"""def facture_ajout(request, pk):
    fournisseur = get_object_or_404(Fournisseurs, pk=pk)
    if request.method == 'POST':
        form = FactureForm(request.POST, request.FILES)
        if form.is_valid():
            facture = form.save(commit=False)
            facture.fournisseur = fournisseur
            facture.save()
            facture.clean()
            facture=FactureForm()
            
    else:
        form = FactureForm()
    return render(request, 'facture_ajout.html', {'form': form, 'fournisseur': fournisseur})"""

from AchatApp.models import Facture
def factures_detail(request, pk):
   
    fournisseur = get_object_or_404(Fournisseurs, pk=pk)
    factures = Facture.objects.filter(fournisseur=fournisseur).order_by('-date_creation')
    return render(request, 'factures_detail.html', {'fournisseur': fournisseur, 'factures': factures,'fournisseurs':Fournisseurs.objects.all()})

2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/templates/ajout_fournisseurs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajout Fournisseur</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</head>
<body>
    {% load static %}
    <h1>Ajouter un Fournisseur et une Facture</h1>
    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        {% csrf_token %}
        {{ fournisseur_form.as_p }}
    <button type = sumbit class="save btn btn-default">Sauvegarder</button>
    <a href="{% url 'FournisseursApp:fournisseurs' %}" class="btn btn-secondary">Retour</a>
</form>
</body>
</html><!-- creer_fournisseur_facture.html -->


2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/templates/facture_ajout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ajouter une Facture</title>
</head>
<body>
    <h1>Ajouter une facture pour {{ fournisseur.Raison_social }}</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Enregistrer</button>
    <a href="{% url 'FournisseursApp:fournisseurs' %}" class="btn btn-secondary">Annuler</a>
  </form>
</body>
</html>

2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/templates/factures_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detail des Factures</title>
</head>
<body>
    <h1>Factures pour {{ fournisseur.Raison_social }}</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Numéro</th>
        <th>Date de création</th>
        <th>Montant</th>
        <th>Versement</th>
        <th>Dette</th>
        <th>Telecharger</th>
      </tr>
    </thead>
    <tbody>
      
      {% for facture in factures %}
        <tr>
          <td>{{ facture.pk }}</td>
          <td>{{ facture.date_creation|date:"d/m/Y H:i" }}</td>
          <td>{{ facture.montant }}</td>
          <td>{{ facture.Versement }}</td>
          <td>{{ facture.Dette}}</td>
          
            {% if facture.fichier %}
            <td> <a href="{{ facture.fichier.url }}" class="btn btn-primary">Télécharger</a>
          </td>
            
            {% else %}
            <td> Pas de Facture</td>
            {% endif %}
        </tr>
      {% empty %}
        <tr>
          <td colspan="4">Aucune facture pour ce fournisseur.</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
 
  <a href="{% url 'FournisseursApp:fournisseurs' %}" class="btn btn-secondary">Retour à la liste des fournisseurs</a>
</body>
</html>

2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/templates/fournisseurs.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fournisseurs</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <form method="get" action="{% url 'FournisseursApp:search_fournisseurs' %}">
        <div class="input-group mb-3">
            <input type="text" class="form-control" placeholder="Rechercher par raison sociale ou numéro de téléphone" name="search_query">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="submit">Rechercher</button>
            </div>
        </div>
    </form>
    
      
  
    <button type = sumbit class="save btn btn-default"><a href="{% url 'FournisseursApp:ajout_fournisseurs' %}">Ajouter un Fournisseur</a></button>
    <div class="main">
      <div class="container">
      <table  class="table mx-auto", border="2">
        <thead>
          <tr>
            <th>
              <a href="{% url 'FournisseursApp:tri_fournisseurs' 'id' %}">ID</a>
          </th>
            <th scope="col"><a href="{% url 'FournisseursApp:tri_fournisseurs' 'Raison_social' %}">Raison social</a></th>
            <th scope="col"><a href="{% url 'FournisseursApp:tri_fournisseurs' 'email' %}">Email</a></th>
            <th scope="col"><a href="{% url 'FournisseursApp:tri_fournisseurs' 'Numero_Telephone' %}">Numero Telphone</a></th>
            <th scope="col"><a href="{% url 'FournisseursApp:tri_fournisseurs' 'Fax' %}">Fax</a></th>
            <th scope="col"><a href="{% url 'FournisseursApp:tri_fournisseurs' 'Versement' %}">Versement</a></th>
            <th scope="col"><a href="{% url 'FournisseursApp:tri_fournisseurs' 'Dette' %}">Dette</a></th>
            <th scope="col">Facture Transaction</th>            
            <th scope="col">Supprimer</th>
            <th scope="col">Modifier</th>
            
          </tr>
        </thead>
        <tbody>
          {% if fournisseurs %}
          {% for produit in fournisseurs%}
          
                <tr>
                    <td>{{ produit.id }}</td>
                    <td>{{ produit.Raison_social }}</td>
                    <td>{{produit.email}}</td>
                    <td>{{ produit.Numero_Telephone}}</td>
                    <td>{{ produit.Fax}}</td>
                    <td>{{ produit.Versement }}</td>
                    <td>{{ produit.Dette }}</td>
               <td>  <a href="{% url 'FournisseursApp:factures_detail' produit.id %}" class="btn">Détail</a> </td>
                  <br>
                  <br>
                    <td><a href="{% url 'FournisseursApp:supprimer_fournisseur' produit.id %}">Supprimer</a></td>
                    <td><a href="{% url 'FournisseursApp:modifier_fournisseur' produit.id %}">Modifier</a></td>
                </td>
                    
            </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="8">Aucun fournisseur n'a été trouvé.</td>
            
          </tr>
        {% endif %}

        
          
          
        </tbody>
      </table>
    
    </div>
    </div>

    
   
</body>
</html>

2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/templates/modifier_fournisseur.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modifier fournisseur</title>
</head>
<body>
    <h1>Modifier un fournisseur</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Modifier" class="btn btn-primary">
        <a class="btn btn-secondary" href="{% url "FournisseursApp:fournisseurs" %}" role="button">Annuler</a>

    </form>
</body>
</html>

2022-l3l1/tags/siteWeb.2/siteWeb/src/FournisseursApp/templates/supprimer_fournisseurs.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Supprimer Fournisseur</title>
</head>
<body>
    <h1>Supprimer un fournisseur</h1>
<p>Êtes-vous sûr de vouloir supprimer le fournisseur "{{ Fournisseur.Raison_social }}" ?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Confirmer la suppression</button>
  <a href="{% url 'FournisseursApp:fournisseurs' %}" class="btn btn-secondary">Annuler</a>
</form>
</body>
</html>