2022-l3l1/branches/siteWeb/src/StatApp/urls.py
"""
all the urls used by  StatApp

"""

from django.urls import path
from . import views


app_name = 'StatApp'

urlpatterns = [
    path('statistique/', views.all_stat, name="statistique"),

]

2022-l3l1/branches/siteWeb/src/siteWeb/urls.py
from django.contrib import admin
from django.urls import path, include

import VenteApp
import ProduitApp
import ClientApp
import AchatApp
import FournisseursApp
import StatApp




from ClientApp import views
from ProduitApp import views
from AchatApp import views
from .views import index,  produit_en_rupture, venue_pdf, loginPage, registerPage, logOutUser, achat, alertesStock, client, fournisseur, produit
from .views import vente
from FournisseursApp import views
from StatApp import views

from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('login/', loginPage, name="login"),
    path('logout/', logOutUser, name="logout"),
    
    path('alertes/', produit_en_rupture, name="alertes"),
    path('client/', client, name="client"),
    path('compte/', registerPage, name="compte"),
    path('fournisseur/', fournisseur, name="fournisseur"),
    path('vente/', vente, name="vente"),
    

    path("", index, name="index"),

    path('venue_pdf/', venue_pdf, name="venue_pdf"),

    #CLIENT URL
    path('', include('ClientApp.urls')),

    #VENTE URL
    path('', include('VenteApp.urls')),

    #PRODUIT URL
    path('', include('ProduitApp.urls')),


    path('admin/', admin.site.urls),
    #FournisseurApp
    
    path('',include(('FournisseursApp.urls','FournisseursApp'),namespace='FournisseursApp')),

    path('fournisseurs/',FournisseursApp.views.index,name='FournisseursApp'),
    path('ajout_fournisseurs/',FournisseursApp.views.ajout_fournisseurs,name='ajout_fournisseurs'),
    path('fournisseurs/supprimer/<int:pk>/', FournisseursApp.views.FournisseurDeleteView.as_view(), name='supprimer_fournisseur'),
    #AchatApp
    path('achat/',AchatApp.views.index,name='achat'),
    path('',include(('AchatApp.urls','AchatApp'),namespace='AchatApp')),
    path('ajouter_produits', AchatApp.views.ajouter_produits, name='ajouter_produits'),
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
    path('<int:pk>/delete/', AchatApp.views.AchatDeleteView.as_view(), name='supprimer_achat'),
    path('<int:pk>/update/', AchatApp.views.AchatUpdateView.as_view(), name='modifier_achat'),

    #Stat
    path('statistique/',StatApp.views.all_stat, name="statistique"),
]

2022-l3l1/branches/siteWeb/src/StatApp/models.py
from django.db import models

# Create your models here.

2022-l3l1/branches/siteWeb/src/StatApp/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

class DateForm(forms.Form):
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    start_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    end_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

2022-l3l1/branches/siteWeb/src/StatApp/views.py
from django.shortcuts import render
from ProduitApp.models import ProduitBrut, Produit, Categorie, Cadre, AutreProduit, CategorieFer,HistoriquePrixAchatQuintal
from FournisseursApp.models import Fournisseurs
from ClientApp.models import Client
from AchatApp.models import Achat
from StatApp.forms import DateForm
from VenteApp.models import Article, Commande, ArticleAutre, ArticleCadre
from django.db.models import Count,Sum



# Create your views here.


def statistique(request):
    return render(request, "StatApp/statistique.html")



def all_stat(request):
    # Informations produits
    nb_categorie = Categorie.objects.count()
    nb_produit = Produit.objects.count()
    nb_autre_produit = AutreProduit.objects.count()


    # Top 5 des cadres par prix
    labels1 = []
    data1 = []
    queryset1 = Cadre.objects.order_by('-prix')[:5]
    for cadre in queryset1:
        labels1.append(cadre.cadre_choix)
        data1.append(cadre.prix)

    #nombre de cadre
    nb_cadre = Cadre.objects.count()

    # Consommation total des cadres
    consommation_total = Cadre.objects.aggregate(Sum('consommation_sans_chute'))['consommation_sans_chute__sum']

    # Prix total des cadres
    prix_total_cadre = Cadre.objects.aggregate(Sum('prix'))['prix__sum']

    # Prix service total des cadres confectionnés
    prix_service_total= Cadre.objects.aggregate(Sum('prix_service'))['prix_service__sum']



    # Total de vente
    prix_total_vente = 0
    #total prix de toutes les commandes
    for commande in Commande.objects.all():
        articles_brut = commande.article_set.all()
        prix_article = sum(article.price for article in articles_brut)

        articles_cadre = commande.articlecadre_set.all()
        prix_cadre = sum(article.price for article in articles_cadre)

        articles_autre = commande.articleautre_set.all()
        prix_autre_produit = sum(article.price for article in articles_autre)
        prix_total_vente += prix_article + prix_autre_produit +prix_cadre


    # Total de dette client
    dette_client = Client.objects.aggregate(Sum('dette'))['dette__sum']
    # Total de dette fournisseur
    dette_fournisseur = Fournisseurs.objects.aggregate(Sum('Dette'))['Dette__sum']

    # nombre de fournisseur
    nb_fournisseur = Fournisseurs.objects.count()

    # nombre de client
    nb_client = Client.objects.count()
    # dette de client
    nb_dette = Client.objects.aggregate(Sum('dette'))['dette__sum']
    # Top 5 dette de client
    labels3 = []
    data3 = []
    queryset3 = Client.objects.order_by('-dette')[:5]
    for client in queryset3:
        labels3.append(client.prenom)
        data3.append(client.dette)


    # Prix total des achats
    prix_total_achat = Achat.objects.aggregate(Sum('prix_total'))['prix_total__sum']

    # Top 5 des fournisseurs par nombre d'achats

    #labels8= []
    #data8 = []
    #queryset = Achat.objects.values('fournisseur__nom').annotate(total_achats=Count('id')).order_by('-total_achats')[:5]
    #for fournisseur in queryset:
    #    labels8.append(fournisseur['fournisseur__nom'])
    #    data8.append(fournisseur['total_achats'])

    # Quantité des articles de la commande

    '''
    # tous les cadres pour chaque commande
    labels9 = []
    data9 = []
    commandes = Commande.objects.all()
    quantite_totale = commandes.aggregate(total_quantite=Sum('articlecadre__quantite'))
    labels9.append('Total')
    data9.append(quantite_totale['total_quantite'])
    for commande in commandes:
        articles = commande.articlecadre_set.all()
        for article in articles:
            labels9.append(str(article.cadre))
            data9.append(article.quantite)
    
    '''

    #regroupe chaque cadre de chaque commande
    labels9 = []
    data9 = []
    cadre_quantites = {}

    commandes = Commande.objects.all()
    quantite_totale = commandes.aggregate(total_quantite=Sum('articlecadre__quantite'))
    labels9.append('Total')
    data9.append(quantite_totale['total_quantite'])

    for commande in commandes:
        articles = commande.articlecadre_set.all()
        for article in articles:
            cadre_nom = str(article.cadre)
            if cadre_nom not in cadre_quantites:
                cadre_quantites[cadre_nom] = article.quantite
            else:
                cadre_quantites[cadre_nom] += article.quantite

    for cadre_nom, quantite in cadre_quantites.items():
        labels9.append(cadre_nom)
        data9.append(quantite)




    '''
    #tous les articles bruts pour chaque commande
    labels10 = []
    data10 = []
    commandes = Commande.objects.all()
    quantite_totale = commandes.aggregate(total_quantite=Sum('article__quantite'))
    labels10.append('Total')
    data10.append(quantite_totale['total_quantite'])
    for commande in commandes:
        articles = commande.article_set.all()

        for article in articles:
            labels10.append(str(article.produit))
            data10.append(article.quantite)
    '''

    # tous les articles bruts pour chaque commande
    labels10 = []
    data10 = []
    produit_quantites = {}

    commandes = Commande.objects.all()
    quantite_totale = commandes.aggregate(total_quantite=Sum('article__quantite'))
    labels10.append('Total')
    data10.append(quantite_totale['total_quantite'])

    for commande in commandes:
        articles = commande.article_set.all()
        for article in articles:
            produit_nom = str(article.produit)
            if produit_nom not in produit_quantites:
                produit_quantites[produit_nom] = article.quantite
            else:
                produit_quantites[produit_nom] += article.quantite

    for produit_nom, quantite in produit_quantites.items():
        labels10.append(produit_nom)
        data10.append(quantite)

    #Top 5 autre produit
    labels11 = []
    data11 = []
    autre_produit_quantites = {}

    commandes = Commande.objects.all()

    for commande in commandes:
        articles = commande.articleautre_set.all()
        for article in articles:
            autre_produit_nom = str(article.produit)
            if autre_produit_nom not in autre_produit_quantites and autre_produit_nom != 'AutreProduit':
                autre_produit_quantites[autre_produit_nom] = article.quantite
            elif autre_produit_nom != 'AutreProduit':
                autre_produit_quantites[autre_produit_nom] += article.quantite

    top_5_produits = sorted(autre_produit_quantites.items(), key=lambda x: x[1], reverse=True)[:5]

    for produit, quantite in top_5_produits:
        labels11.append(produit)
        data11.append(quantite)


    """
        date_form = DateForm(request.GET or None)
    if date_form.is_valid():
        date = date_form.cleaned_data['date']
        start_date = date_form.cleaned_data['start_date']
        end_date = date_form.cleaned_data['end_date']
        commandes = Commande.objects.filter(date_creation__date=date, date_creation__range=(start_date, end_date))
        prix_total_vente = 0
        for commande in commandes:
            articles_brut = commande.article_set.all()
            prix_article = sum(article.price for article in articles_brut)

            articles_cadre = commande.articlecadre_set.all()
            prix_cadre = sum(article.price for article in articles_cadre)

            articles_autre = commande.articleautre_set.all()
            prix_autre_produit = sum(article.price for article in articles_autre)

            prix_total_vente += prix_article + prix_autre_produit + prix_cadre
    else:
        prix_total_vente = None

    context = {
        'nb_categorie': nb_categorie,
        'nb_produit': nb_produit,
        'nb_autre_produit': nb_autre_produit,
        # ...
        'prix_total_vente': prix_total_vente,
        'date_form': date_form,
    }

    """




    return render(request, 'StatApp/statistique.html', {
        'nb_categorie':nb_categorie,
        'nb_produit':nb_produit,
        'nb_autre_produit':nb_autre_produit,
        'labels1': labels1,
        'data1': data1,
        'nb_cadre':nb_cadre,
        'consommation_total': consommation_total,
        'prix_total_cadre': prix_total_cadre,
        'prix_service_total':prix_service_total,


        'prix_total_vente': prix_total_vente,
        'prix_total_achat': prix_total_achat,

        'nb_fournisseur':nb_fournisseur,

        'nb_client':nb_client,
        'nb_dette':nb_dette,
        'labels3': labels3,
        'data3': data3,



        'dette_client':dette_client,
        'dette_fournisseur': dette_fournisseur,

        #'labels8': labels8,
        #'data8': data8,

        'labels9': labels9,
        'data9': data9,

        'labels10': labels10,
        'data10': data10,

        'labels11': labels11,
        'data11': data11,
    })



2022-l3l1/branches/siteWeb/src/StatApp/templates/StatApp/statistique.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statistiques</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/decimal.js/10.2.0/decimal.min.js"></script>
</head>
<body>
<h1>Statistiques</h1>
<br><br>
<h2>Produit</h2>
<div style="display: flex; justify-content: space-around;">
    <div id="produit1" style="width: 40%;">
        <canvas id="top5_prix_cadre"></canvas>
    </div>
    <div id="produit2" style="width: 40%;">
        <canvas id="prix_consommation"></canvas>
    </div>
    <div id="produit3" style="width: 40%;">
        <canvas id="information_produit"></canvas>
    </div>
</div>

<h2>Vente et achat</h2>

<div style="display: flex; justify-content: space-around;">
    <div id="achat_vente1" style="width: 40%;">
        <canvas id="achat_vente"></canvas>
    </div>

    <div id="article_cadre1" style="width: 40%;">
        <canvas id="article_cadre"></canvas>
    </div>

    <div id="article_brut1" style="width: 40%;">
        <canvas id="article_brut"></canvas>
    </div>

    <div id="article_autre1" style="width: 40%;">
        <canvas id="article_autre"></canvas>
    </div>
</div>

<h2>Client et fournisseur</h2>
<div style="display: flex; justify-content: space-around;">
    <div id="client1" style="width: 40%;">
        <canvas id="client_fournisseur"></canvas>
    </div>

    <div id="client2" style="width: 40%;">
        <canvas id="dette_client_fournisseur"></canvas>
    </div>

    <div id="client4" style="width: 40%;">
        <canvas id="top5_dette_client"></canvas>
    </div>

    <div id="client5" style="width: 40%;">
        <canvas id="top5_fournisseur"></canvas>
    </div>

</div>
<br>
<!--
<form method="get">
    {{ date_form.as_p }}
    <label for="id_start_date">Date de début :</label>
    <input type="date" name="start_date" id="id_start_date">
    <label for="id_end_date">Date de fin :</label>
    <input type="date" name="end_date" id="id_end_date">
    <button type="submit">Afficher</button>
</form>


{% if prix_total_vente is not None %}
    <p>Prix total des ventes pour le {{ date_form.cleaned_data.date|date:"d/m/Y" }} : {{ prix_total_vente }} €</p>
{% else %}
    <p>Veuillez sélectionner une date pour afficher le prix total des ventes.</p>
{% endif %}
-->

<script>
    //graphe pour top 5 prix cadre
    var data1 = {
        datasets: [{
            data: {{ data1|safe }},
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
                '#000000', // noir
                '#800080'  // violet
            ],
            label: 'Prix des top 5 cadres'
        }],
        labels: {{ labels1|safe }}
    };
    var options1 = {
        responsive: true,
        title: {
            display: true,
            text: "Les cadres les plus chers (Top 5)"
        }
    };
    var config1 = {
        type: 'line',
        data: data1,
        options: options1
    };


    //Information cadres
    var data2 = {
        datasets: [{
            data: [{{ prix_total_cadre }},{{ consommation_total }}, {{ prix_service_total }}, {{ nb_cadre }} ],
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
                '#000000', // noir
            ],
            label: 'Métadonnées de cadre'
        }],
        labels: ['Prix total', 'Consommation totale', 'Prix de service','Nombre de cadre']
    };

    var options2 = {
        responsive: true,
        maintainAspectRatio: false,
        title: {
            display: true,
            text: "Informations sur les cadres",
        },
    }
    var config2 = {
        type: 'bar',
        data: data2,
        options: options2
    };

    // top 5 dette client
    var data3 = {
        datasets: [{
            data: {{ data3|safe }},
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
                '#000000', // noir
                '#800080'  // violet
            ],
            label: 'top 5 dette client'
        }],
        labels: {{ labels3|safe }}
    };
    var options3 = {
        responsive: true,
        title: {
            display: true,
            text: "Top 5 client qui ont le plus de dette"
        }
    };
    var config3 = {
        type: 'pie',
        data: data3,
        options: options3
    };


    //Client et fournisseur
    var data4 = {
        datasets: [{
            data: [{{ nb_client }},{{ nb_fournisseur }} ],
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
                '#000000', // noir
            ],
            label: 'Client et fournisseur'
        }],
        labels: ['Client', 'Fournisseur']
    };
    var options4 = {
        responsive: true,
        title: {
            display: true,
            text: "Répartition des clients et fournisseurs"
        }
    };
    var config4 = {
        type: 'pie',
        data: data4,
        options: options4
    };

    //Informations produits
    var data5 = {
        datasets: [{
            data: [{{ nb_produit }},{{ nb_autre_produit }},{{ nb_categorie }} ],
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
            ],
            label: 'Informations produits'
        }],
        labels: ['Produit', 'Autre produit', 'Categorie']
    };
    var options5 = {
        responsive: true,
        title: {
            display: true,
            text: "Informations produits"
        }
    };
    var config5 = {
        type: 'pie',
        data: data5,
        options: options5
    };



    // top 5 dette client
    var data3 = {
        datasets: [{
            data: {{ data3|safe }},
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
                '#000000', // noir
                '#800080'  // violet
            ],
            label: 'Top 5 client qui ont le plus de dette'
        }],
        labels: {{ labels3|safe }}
    };
    var options3 = {
        responsive: true,
        title: {
            display: true,
            text: "Top 5 client qui ont le plus de dette"
        }
    };
    var config3 = {
        type: 'pie',
        data: data3,
        options: options3
    };





    //dette total client et fournisseur
    var data7 = {
        datasets: [{
            data: [{{ dette_client }},{{ dette_fournisseur }}],
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
            ],
            label: 'Dette total de client et fournisseur'
        }],
        labels: ['Client', 'Fournisseur']
    };
    var options7 = {
        responsive: true,
        title: {
            display: true,
            text: "Dette total de client et fournisseur"
        }
    };
    var config7 = {
        type: 'pie',
        data: data7,
        options: options7
    };



/*
    var data8 = {
        datasets: [{
            data: [{{ data8|safe }}],
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
                '#000000', // noir
                '#800080'  // violet
            ],
            label: 'top 5 meilleur fournisseur'
        }],
        labels: {{ labels8|safe }}
    };
    var options8 = {
        responsive: true,
        title: {
            display: true,
            text: "top 5 meilleur fournisseur"
        }
    };
    var config8 = {
        type: 'pie',
        data: data8,
        options: options8
    };
*/



    // cadre plus vendu
    var data9 = {
        datasets: [{
            data: {{ data9|safe }},
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
                '#000000', // noir
                '#800080',  // violet
                '#FFFF00', // jaune
                '#FFA500', // orange
                '#FFFFFF', // blanc
                '#FFC0CB', // rose
                '#808080' // gris
            ],
            label: 'Total'
        }],
        labels: {{ labels9|safe }}
    };
    var options9 = {
        responsive: true,
        title: {
            display: true,
            text: "Les cadres les plus vendus"
        }
    };
    var config9 = {
        type: 'bar',
        data: data9,
        options: options9
    };



    // article brut
    var data10 = {
        datasets: [{
            data: {{ data10|safe }},
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
                '#000000', // noir
                '#800080', // violet
                '#FFFF00', // jaune
                '#FFA500', // orange
                '#FFFFFF', // blanc
                '#FFC0CB', // rose
                '#808080' // gris
            ],
            label: 'brut plus vendu'
        }],
        labels: {{ labels10|safe }}
    };
    var options10 = {
        responsive: true,
        title: {
            display: true,
            text: "Les produits bruts plus vendus"
        }
    };
    var config10 = {
        type: 'pie',
        data: data10,
        options: options10
    };




    // autre article
    var data11 = {
        datasets: [{
            data: {{ data11|safe }},
            backgroundColor: [
                '#0000FF', // bleu
                '#FF0000', // rouge
                '#008000', // vert
                '#000000', // noir
                '#800080', // violet
            ],
            label: 'autre produit top 5'
        }],
        labels: {{ labels11|safe }}
    };
    var options11 = {
        responsive: true,
        title: {
            display: true,
            text: "Top 5 des autres produits les plus vendus"
        }
    };
    var config11 = {
        type: 'pie',
        data: data11,
        options: options11
    };


    //achat et vente
    var data12 = {
        datasets: [{
            data: [{{ prix_total_vente }} - {{ prix_total_achat }}, {{ prix_total_vente }},{{ prix_total_achat }}, {{ nb_vente }}  ],
            backgroundColor: [
                '#008000', // vert
                '#0000FF', // bleu - représente le Prix total
                '#FF0000', // rouge - représente la Consommation totale

            ],
            label: 'Bénéfices',
        }],
        labels: ['Bénéfices','Total de vente', 'Total d\'achat']

    };
    var options12 = {
        responsive: true,
        title: {
            display: true,
            text: "Total vente et achat"
        },
        legend: {
            display: true,
            labels: {
                fontColor: 'black'
            }
        }
    };
    var config12 = {
        type: 'bar',
        data: data12,
        options: options12
    };




    window.onload = function() {
        var ctx1 = document.getElementById('top5_prix_cadre').getContext('2d');
        window.myPie1 = new Chart(ctx1, config1);
        var ctx2 = document.getElementById('prix_consommation').getContext('2d');
        window.myPie2 = new Chart(ctx2, config2);
        var ctx3 = document.getElementById('top5_dette_client').getContext('2d');
        window.myPie3 = new Chart(ctx3, config3);

        var ctx4 = document.getElementById('client_fournisseur').getContext('2d');
        window.myPie4 = new Chart(ctx4, config4);

        var ctx5 = document.getElementById('information_produit').getContext('2d');
        window.myPie5 = new Chart(ctx5, config5);



        var ctx7 = document.getElementById('dette_client_fournisseur').getContext('2d');
        window.myPie7 = new Chart(ctx7, config7);

       // var ctx8 = document.getElementById('top5_fournisseur').getContext('2d');
       // window.myPie8 = new Chart(ctx8, config8);

        var ctx9 = document.getElementById('article_cadre').getContext('2d');
        window.myPie9 = new Chart(ctx9, config9);

        var ctx10 = document.getElementById('article_brut').getContext('2d');
        window.myPie10 = new Chart(ctx10, config10);

        var ctx11 = document.getElementById('article_autre').getContext('2d');
        window.myPie11 = new Chart(ctx11, config11);

        var ctx12 = document.getElementById('achat_vente').getContext('2d');
        window.myPie12 = new Chart(ctx12, config12);
    };
</script>
</body>
</html>