2022-l3l1/trunk/siteWeb/src/FournisseursApp/urls.py
from django.contrib import admin
from django.urls import path, include
from FournisseursApp import views
from .views import FournisseurUpdateView

from FournisseursApp.views import FournisseurDeleteView
urlpatterns=[
    path('fournisseurs/',views.index,name='fournisseurs'),
    path('ajout_fournisseurs/', views.ajout_fournisseurs, name='ajout_fournisseurs'),
   path('fournisseurs/supprimer/<int:pk>/', FournisseurDeleteView.as_view(), name='supprimer_fournisseur'),
   path('<int:pk>/modifier/', FournisseurUpdateView.as_view(), name='modifier_fournisseur'),
   path('fournisseurs/search/', views.search_fournisseurs, name='search_fournisseurs'),
path('tri_fournisseurs/<str:tri>/', views.tri_fournisseurs, name='tri_fournisseurs'),
path('fournisseurs/factures_detail/<int:pk>/', views.factures_detail, name='factures_detail'),

]
"""path('fournisseurs/facture_ajout/<int:pk>/', views.facture_ajout, name='facture_ajout'),
path('fournisseurs/factures_detail/<int:pk>/', views.factures_detail, name='factures_detail'),"""




2022-l3l1/trunk/siteWeb/src/ProduitApp/urls.py
"""
all the urls used by  ProduitApp

"""

from django.urls import path
from . import views
from .views import modifier_produit, produit_detail,supprimer_produit_brut,supprimer_autre_produit, autre_produit_detail,modifier_autre_produit,modifier_categorie,supprimer_categorie
from django.conf import settings
from django.conf.urls.static import static

app_name = 'ProduitApp'

urlpatterns = [
    path('produit_brut/',views.produit_brut,name='produit_brut'),
   # path('produit_brut/add/', views.add_produit_brut, name='add_produit_brut'),
    path('produit_brut/modifier/<int:pk>/', modifier_produit.as_view(), name='modifier_produit'),
    path('produit_brut/detail/<int:pk>/', produit_detail.as_view(), name='produit_detail'),
    path('produit_brut/supprimer/<int:pk>/', supprimer_produit_brut.as_view(), name='supprimer_produit_brut'),
    path('historique_prix_achat_quintal/<int:pk>/', views.historique_prix_achat_quintal, name='historique_prix_achat_quintal'),


    path('autre_produit/',views.autre_produit,name='autre_produit'),
    path('autre_produit/modifier/<int:pk>/', modifier_autre_produit.as_view(), name='modifier_autre_produit'),
    path('autre_produit/add/', views.add_autre_produit, name='add_autre_produit'),
    path('autre_produit/detail/<int:pk>/', autre_produit_detail.as_view(), name='autre_produit_detail'),
    path('autre_produit/supprimer/<int:pk>/', supprimer_autre_produit.as_view(), name='supprimer_autre_produit'),




    path('cadre/',views.cadre ,name='cadre'),
    path('cadre/create_cadre', views.createCadre, name='create_cadre'),
    path('cadre/supprimer/<int:id>/', views.supprimer_cadre, name='supprimer_cadre'),
    path('cadre/modifier/<int:pk>/', views.modifier_cadre.as_view(), name='modifier_cadre'),
    path('tri_cadre/<str:tri>/', views.tri_cadre, name='tri_cadre'),


    path('produitApp/', views.index, name='produitApp'),


    path('categorie/', views.categorie, name='categorie'),
    path('create_categorie/', views.create_category, name='create_categorie'),
    path('categorie/modifier/<int:pk>/', modifier_categorie.as_view(), name='modifier_categorie'),
    path('categorie/supprimer/<int:pk>/',supprimer_categorie.as_view(),name='supprimer_categorie'),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

2022-l3l1/trunk/siteWeb/src/StatApp/urls.py
"""
all the urls used by  StatApp

"""

from django.urls import path
from . import views


app_name = 'StatApp'

urlpatterns = [
    path('statistique/', views.all_stat, name="statistique"),

]

2022-l3l1/trunk/siteWeb/src/siteWeb/urls.py
from django.contrib import admin
from django.urls import path, include

import VenteApp
import ProduitApp
import ClientApp
import AchatApp
import FournisseursApp




from ClientApp import views
from VenteApp import views
from ProduitApp import views
from AchatApp import views
from .views import index, venue_pdf, loginPage, registerPage, logOutUser, achat, alertesStock, client, fournisseur
from .views import vente
from FournisseursApp import views


urlpatterns = [
    path('login/', loginPage, name="login"),
    path('logout/', logOutUser, name="logout"),
    
    path('alertes/', alertesStock, name="alertes"),
    path('client/', client, name="client"),
    path('compte/', registerPage, name="compte"),
    path('fournisseur/', fournisseur, name="fournisseur"),
    path('vente/', vente, name="vente"),

    path("", index, name="index"),

    path('venue_pdf/', venue_pdf, name="venue_pdf"),
    path('compteApp/', ClientApp.views.index, name='compteApp'),

    #VENTE URL
    path('venteApp/', include('VenteApp.urls',namespace='venteApp')),
    path('proformat/', VenteApp.views.proformat, name="proformat"),
    path('create_order/', VenteApp.views.createOrder, name="create_order"),
    path('update_order/<str:pk>/', VenteApp.views.updateOrder, name="update_order"),
    path('delete_order/<str:pk>/', VenteApp.views.deleteOrder, name="delete_order"),
    path('recherche/', VenteApp.views.searchBar, name="search"),

    #PRODUIT URL
    path('', include('ProduitApp.urls')),

    path('', include('StatApp.urls')),

    path('admin/', admin.site.urls),
    #FournisseurApp
    
    path('',include(('FournisseursApp.urls','FournisseursApp'),namespace='FournisseursApp')),

    path('fournisseurs/',FournisseursApp.views.index,name='FournisseursApp'),
    path('ajout_fournisseurs/',FournisseursApp.views.ajout_fournisseurs,name='ajout_fournisseurs'),
    path('fournisseurs/supprimer/<int:pk>/', FournisseursApp.views.FournisseurDeleteView.as_view(), name='supprimer_fournisseur'),
    #AchatApp
    path('achat/',AchatApp.views.index,name='achat'),
    path('',include(('AchatApp.urls','AchatApp'),namespace='AchatApp')),
     path('ajouter_facture/fournisseur/<int:fournisseur_id>/achat/<int:achat_id>/', AchatApp.views.ajouter_facture, name='ajouter_facture'),
]

2022-l3l1/trunk/siteWeb/src/siteWeb/forms.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm



class CreationUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']

2022-l3l1/trunk/siteWeb/src/siteWeb/views.py
from django.shortcuts import render, redirect
from django.http import FileResponse, HttpResponseRedirect
from .forms import CreationUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth.decorators import login_required

import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter

@login_required(login_url="login")
def index(request):
    return render(request, "siteWeb/index.html")

def achat(request):
    return render(request, "AchatApp/achat.html")

def alertesStock(request):
    return render(request, "siteWeb/alertesStock.html")

def client(request):
    return render(request, "siteWeb/client.html")

def fournisseur(request):
    return render(request, "FournisseurApp/fournisseur.html")

def produit(request):
    return render(request, "siteWeb/produit.html")


def vente(request):
    return render(request, "siteWeb/vente.html")


def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('index')
        else:
            messages.info(request,'Username or password is incorrect' )
    context = {}
    return render(request, "siteWeb/login.html",context)

def registerPage(request):

    form = CreationUserForm()

    if request.method == 'POST':
        form = CreationUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for '+ user )
            return redirect('index')
    context = {'form' : form}
    return render(request, "siteWeb/register.html", context)

def logOutUser(request):
    logout(request)
    return redirect('login')

def venue_pdf(request):

    buf = io.BytesIO()

    c = canvas.Canvas(buf, pagesize=letter,bottomup=0)

    textob = c.beginText()
    textob.setTextOrigin(inch, inch)
    textob.setFont('Helvetica', 14)

    lines = ["This is line 1",
             "This is line 2",
             "This is line 3",
             ]
    for line in lines:
        textob.textLine(line)

    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)

    return FileResponse(buf, as_attachment=True, filename='pythonPDF.pdf')

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/achat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Achat</title>
</head>
<body>
    <h1>Achat</h1>
</body>
</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/alertesStock.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Alertes de fin de stock</title>
</head>
<body>
    <h1>Alertes de fin de stock</h1>
</body>
</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/client.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Client</title>
</head>
<body>
    {% include "ClientApp/index.html" %}
</body>
</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/fournisseur.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Fournisseur</title>
</head>
<body>
    <h1>Fournisseur</h1>
</body>
</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/index.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<body>



      <nav id="navbar" class="navbar">
          <div class="logout">
            <a href="{% url 'login' %}">Déconnexion</a>
          </div>
      </nav>


          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="100">
            <div class="icon-box">
              <div class="icon"><i class="bi bi-bag"></i></div>
              <h4 class="title"><a href="{% url 'AchatApp:achat' %}" class="stretched-link">achat</a></h4>
            </div>
          </div>


          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="200">
            <div class="icon-box">
              <div class="icon"><i class="bi bi-cash-coin"></i></div>
              <h4 class="title"><a href="{% url 'vente' %}" class="stretched-link">vente</a></h4>
            </div>
          </div>


          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="300">
            <div class="icon-box">
              <div class="icon"><i class="bi bi-person-circle"></i></div>
              <h4 class="title"><a href="{%  url 'client' %}" class="stretched-link">client</a></h4>
            </div>
          </div>


          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="400">
            <div class="icon-box">
              <div class="icon"><i class="bi bi-person-lines-fill"></i></div>
              <h4 class="title"><a href="{% url 'FournisseursApp:fournisseurs' %}" class="stretched-link">fournisseur</a></h4>
            </div>
          </div>


          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="500">
            <div class="icon-box">
              <div class="icon"><i class="bi bi-bar-chart-line"></i></div>
              <h4 class="title"><a href="{% url 'StatApp:statistique' %}" class="stretched-link">statistique</a></h4>
            </div>
          </div>

          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="600">
            <div class="icon-box">
              <div class="icon"><i class="bi bi-person-plus"></i></div>
              <h4 class="title"><a href="{% url 'compte' %}" class="stretched-link">création compte</a></h4>
            </div>
          </div>

          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="700">
            <div class="icon-box">
              <div class="icon"><i class="bi bi-box-seam"></i></div>
              <h4 class="title"><a href="{% url 'ProduitApp:produit_brut' %}" class="stretched-link">produit</a></h4>
            </div>
          </div>

          <div class="col-xl-3 col-md-6" data-aos="fade-up" data-aos-delay="800">
            <div class="icon-box">
              <div class="icon"><i class="bi bi-bell"></i></div>
              <h4 class="title"><a href="{% url 'alertes' %}" class="stretched-link">alertes de fin de stock</a></h4>
            </div>
          </div>

</body>

</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/login.html
<!DOCTYPE html>
<html>

<head>
	<title>Connexion</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">Connexion</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Nom d'utilisateur..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Mot de passe..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Connexion">
				   			</div>
					</form>

				</div>
				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}

			</div>
		</div>
	</div>
</body>

</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/produit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Produit</title>
</head>
<body>
    <h1>Produit</h1>
</body>
</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/register.html
<!DOCTYPE html>
<html>

<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Création de compte</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Créer le compte">
				   		</div>
					</form>
				</div>
				{{form.errors}}
			</div>
		</div>
	</div>
	<script>

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/statistique.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Statistique</title>
</head>
<body>
    <h1>Statistique</h1>
</body>
</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TEST FORMS</title>
</head>
<body>
<h2>Gestion Client</h2>
<form enctype="multipart/form-data" method ='POST'>
    {% csrf_token%}
    {{form.as_p}}
    <button type = sumbit class="save btn btn-default">Sauvegarder</button>
</form>
</body>
</html>

2022-l3l1/trunk/siteWeb/src/siteWeb/templates/siteWeb/vente.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vente</title>
</head>
<body>
    <h1>Vente</h1>
</body>
</html>